# Generated by Django 5.2.5 on 2025-08-11 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('PARTICIPANTE', 'Participante'), ('ORGANIZADOR', 'Organizador')], default='PARTICIPANTE', max_length=20)),
                ('fecha_promocion', models.DateTimeField(blank=True, null=True)),
                ('codigo_invitacion_usado', models.CharField(blank=True, max_length=10, null=True)),
                ('apuestas_realizadas', models.IntegerField(default=0)),
                ('promocion_solicitada', models.BooleanField(default=False)),
                ('fecha_solicitud_promocion', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
