# Generated by Django 5.2.5 on 2025-08-11 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_gestionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participante',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADO', 'Pagado y activo'), ('SUSPENDIDO', 'Suspendido temporalmente'), ('ELIMINADO', 'Eliminado de la quiniela')], default='PENDIENTE', help_text='Estado actual del participante', max_length=20),
        ),
        migrations.AddField(
            model_name='participante',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se registró el pago', null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='metodo_pago',
            field=models.CharField(blank=True, help_text='Método de pago utilizado (efectivo, transferencia, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='participante',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto pagado por el participante', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='notas_admin',
            field=models.TextField(blank=True, help_text='Notas privadas del administrador sobre este participante'),
        ),
    ]
